set(CMAKE_SYSTEM_NAME    Windows)
set(CMAKE_SYSTEM_VERSION 10)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CROSS_PREFIX x86_64-w64-mingw32)

find_program(CMAKE_C_COMPILER  NAMES ${CROSS_PREFIX}-gcc     REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES ${CROSS_PREFIX}-windres)
find_program(CMAKE_MAKE_PROGRAM NAMES make gmake             REQUIRED)

find_program(_MINGW_GXX NAMES ${CROSS_PREFIX}-g++)
if(_MINGW_GXX)
    set(CMAKE_CXX_COMPILER "${_MINGW_GXX}")
else()
    set(CMAKE_CXX_COMPILER_FORCED TRUE)
    set(CMAKE_CXX_COMPILER "${CMAKE_C_COMPILER}")
    set(CMAKE_CXX_COMPILER_WORKS 1 CACHE INTERNAL "")
endif()

set(CMAKE_EXE_LINKER_FLAGS_INIT    "-static -static-libgcc")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static -static-libgcc")

set(CMAKE_FIND_ROOT_PATH
    /usr/${CROSS_PREFIX}
    /usr/lib/gcc/${CROSS_PREFIX}
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)